ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of RPVMSSM_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_737 = ', GC_737
      WRITE(*,2) 'GC_739 = ', GC_739
      WRITE(*,2) 'GC_745 = ', GC_745
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_736 = ', GC_736
      WRITE(*,2) 'GC_921 = ', GC_921
      WRITE(*,2) 'GC_922 = ', GC_922
      WRITE(*,2) 'GC_923 = ', GC_923
      WRITE(*,2) 'GC_924 = ', GC_924
      WRITE(*,2) 'GC_962 = ', GC_962
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_698 = ', GC_698
      WRITE(*,2) 'GC_702 = ', GC_702
      WRITE(*,2) 'GC_706 = ', GC_706
      WRITE(*,2) 'GC_710 = ', GC_710
      WRITE(*,2) 'GC_714 = ', GC_714
      WRITE(*,2) 'GC_718 = ', GC_718
      WRITE(*,2) 'GC_752 = ', GC_752
      WRITE(*,2) 'GC_756 = ', GC_756
      WRITE(*,2) 'GC_760 = ', GC_760
