C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (ProjM(2,1)) * C(51,2) * C(52,1)
C     
      SUBROUTINE FFS1C1P1N_3(F2, F1, COUP,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(3)
      COMPLEX*16 TMP2
      TMP2 = (F2(3)*F1(3)+F2(4)*F1(4))
      S3(3)= COUP*(-CI )* TMP2
      END


